### ISSUE TITLE
Consider converting repo to a template repo

### ISSUE THREAD

**Issue by wayneparrott** [santoshshinde2012/node-boilerplate#10]
Thx for the convenient boilerplate repo.  Going 1 step further please consider converting the repo to serve as a template repo for others to quickly adopt. See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository

**Comment by santoshshinde2012** [comment]
Thank you so much @wayneparrott. Added as a template, now you can use it as a template.
