### ISSUE TITLE
pretty script issue and import/order issue

### ISSUE THREAD

**Issue by chayyccee** [santoshshinde2012/node-boilerplate#170]
when the script `npm run pretty` is executed, it returns an error ` "no files matching the pattern were found: "'src/**/*.ts'" " `.
and there are import order issues in some files.

**Comment by santoshshinde2012** [comment]
Take the latest version and let me know if it does not resolve the problem.

You can check the results of the action workflow here.

[https://github.com/santoshshinde2012/node-boilerplate/runs/6374518648?check_suite_focus=true](https://github.com/santoshshinde2012/node-boilerplate/runs/6374518648?check_suite_focus=true)

**Comment by chayyccee** [comment]
good workflow sir, i definitely have a lot to learn from you.
I have pulled the new changes, but the issue persist, see images below. also
if you don't mind sir, I'd like to contribute and fix it.

![Screenshot 2022-05-11 054534](https://user-images.githubusercontent.com/61959647/167771718-33ac65af-cfaf-4e88-92b5-bb7b4067cae1.png)
![Screenshot 2022-05-11 055048](https://user-images.githubusercontent.com/61959647/167771722-c859ea14-a807-4faf-ae39-8a1d522457c1.png)

**Comment by santoshshinde2012** [comment]
Sure, please create a PR for the dev branch

**Comment by chayyccee** [comment]
ok sir

**Comment by santoshshinde2012** [comment]
> good workflow sir, i definitely have a lot to learn from you. I have pulled the new changes, but the issue persist, see images below. also if you don't mind sir, I'd like to contribute and fix it.
> 
> ![Screenshot 2022-05-11 054534](https://user-images.githubusercontent.com/61959647/167771718-33ac65af-cfaf-4e88-92b5-bb7b4067cae1.png) ![Screenshot 2022-05-11 055048](https://user-images.githubusercontent.com/61959647/167771722-c859ea14-a807-4faf-ae39-8a1d522457c1.png)

I think you are using a different Visual Studio plugin for linting, And use the below line to fix the pretty command.

```
 "pretty": "prettier --write \"src/**/*.ts\"",
 ```

**Comment by chayyccee** [comment]
works fine now.
